baseURL: "https://samdaaepic.netlify.app"
languageCode: "en-us"
title: "About Sam"
theme: hugo-profile

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "About Sam"
  description: My About Me Page
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #     menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Sam."
    subtitle: "Iam a Kid Learning To Code"
    content: "I'm A 15 Years old Kid, learning how to code. I started out my journey of learning linux and programming at the age of 11."
    image: /images/sam.jpg
    button:
      enable: true
      name: "Resume"
      url: "#"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: "https://github.com/SamDaaEpic"
        - icon: fab fa-reddit
          url: "https://www.reddit.com/user/SamDaaEpic"
        - icon: fab fa-twitter
          url: "https://twitter.com/SamDaaEpic"
        - icon: fab fa-discord
          url: "https://discord.com/users/828945469416669195"

  # About
  about:
    enable: true
    title: "About Me"
    image: /images/me.jpg
    content: |-
      I am a 15 years programmer/linux enthusiast/tech enthusiast. I started out my journey in programming and linux when i was 11. Iam currently learning the C Programming Language.

      I am currently working on my first C project a Tic Tac Toe Game.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "C"
        - "C++"
        - "Python"
        - "HTML"
        - "CSS"
        - "LUA"

  # Experience
  experience:
    enable: false
    items:
      - job: "Senior Software Developer"
        company: "Facebook"
        companyUrl: "https://example.com"
        date: "Jan 2022 - present"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://example.com"
        content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

      - job: "Software Developer"
        company: "Amazon"
        companyUrl: "https://example.com"
        date: "Sep 2020 - Dec 2021"
        featuredLink:
          enable: true
          url: "https://example.com"
        info:
          enable: true
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product.

      - job: "Junior Software Developer"
        company: "Apple"
        companyUrl: "https://example.com"
        date: "Jan 2020 - Aug 2020"
        info:
          enable: false
        featuredLink:
          enable: true
          url: "https://example.com"
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product.

      - job: "UI/UX Designer"
        company: "Netflix"
        companyUrl: "https://example.com"
        date: "June 2017 - Nov 2019"
        featuredLink:
          enable: true
          url: "https://example.com"
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product.

      - job: "Product Designer"
        company: "Google"
        companyUrl: "https://example.com"
        date: "Feb 2016 - Mar 2017"
        content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # Education
  education:
    enable: false
    # index: true
    items:
      - title: "Master of Business Administration"
        school:
          name: "University of California, Berkeley"
          url: "https://example.org"
        date: "2013 - 2015"
        GPA: "3.8 out of 5.0"
        content: |-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Massachusetts Institute of Technology"
          url: "https://example.org"
        date: "2009 - 2013"
        GPA: "3.9 out of 5.0"
        content: |-
          I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
          - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
          - Face mask detection using a single convolutional neural network.

          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: "My academic record"
          url: "https://example.com"
      - title: "High School"
        school:
          name: "Thomas Jefferson High School for Science and Technology."
          url: "https://example.org"
        GPA: "4.2 out of 5.0"
        featuredLink:
          enable: true
          url: "https://example.com"

  # Achievements To Be Achieved
  achievements:
    enable: true
    items:
      - title: Become A Programmer
        content: I want to become a C and Java Backend developer.
        url: https://example.com
      - title: Get a Job At Google
        content: I want to work in Google.
      - title: Get a Job At Microsoft When Bored with Google.
        content: After i get bored with the job of google get a job at microsoft.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Create your Own Company
        content: After iam bored with all my jobs, create my own company.

  # projects
  projects:
    enable: true
    items:
      - title: Tic Tac Toe Game in C!
        content: This is my first project with the C programming language.
        image: /images/projects/tictactoe.png
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/SamDaaEpic/Sam-C-Projects
      
      - title: My Awesome Wm Rice made in Lua!
        content: My Awesome Window Manager Rice i created myself in lua. Awesome Window Manager is a highly customizable window manager for powerusers.
        image: /images/projects/desktop.png
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/SamDaaEpic/dotfiles

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: SamDaaEpic@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/SamDaaEpic
      twitter: https://twitter.com/SamDaaEpic
      reddit: https://reddit.com/user/SamDaaEpic
      discord: https://discord.com/users/828945469416669195
